
// 這個檔案是自動生成的，請勿手動修改！
const imageGroups = [
  [
    "img/p1/1.jpg",
    "img/p1/2.jpg",
    "img/p1/3.jpg",
    "img/p1/4.jpg"
  ],
  [
    "img/p2/1.jpg",
    "img/p2/2.jpg",
    "img/p2/3.jpg",
    "img/p2/4.jpg",
    "img/p2/5.jpg",
    "img/p2/6.jpg",
    "img/p2/7.jpg"
  ],
  [
    "img/p3/1.jpg",
    "img/p3/2.jpg",
    "img/p3/3.jpg",
    "img/p3/4.jpg"
  ],
  [
    "img/p4/1.jpg",
    "img/p4/10.jpg",
    "img/p4/11.jpg",
    "img/p4/12.jpg",
    "img/p4/13.jpg",
    "img/p4/14.jpg",
    "img/p4/15.jpg",
    "img/p4/16.jpg",
    "img/p4/2.jpg",
    "img/p4/3.jpg",
    "img/p4/4.jpg",
    "img/p4/5.jpg",
    "img/p4/6.jpg",
    "img/p4/7.jpg",
    "img/p4/8.jpg",
    "img/p4/9.jpg"
  ],
  [
    "img/p5/1.jpg",
    "img/p5/2.jpg",
    "img/p5/3.jpg",
    "img/p5/4.jpg"
  ],
  [
    "img/p6/1.jpg",
    "img/p6/2.jpg",
    "img/p6/3.jpg"
  ],
  [
    "img/p7/1.jpg"
  ]
];
